"""agregue columna pais

Revision ID: 651fb9655400
Revises: f7d6e875bba1
Create Date: 2023-01-27 11:13:46.001001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651fb9655400'
down_revision = 'f7d6e875bba1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('pais', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'pais')
    # ### end Alembic commands ###
