"""eliminar columna estado2

Revision ID: e382d5cae94e
Revises: d7852c2db0b4
Create Date: 2023-01-27 11:10:29.687948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e382d5cae94e'
down_revision = 'd7852c2db0b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
